name: Push CFN to AWS
on: [workflow_dispatch]
jobs:
  Deploy:
    name: Deploy the CFN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Install powershell Module
        shell: pwsh
        run: Install-Module -Name AWS.Tools.CloudFormation -force
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::137150604440:role/RoleForGitHub
          aws-region: eu-west-1
      - name: Call powershell script
        run: pwsh Deploy.ps1
  
    
